name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v2

      - name: Exécuter Ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible-playbook/deploy.yml
          inventory: ansible-playbook/inventory.ini
          key: ${{ secrets.ssh_rsa }}
          remote_user: user